services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MinhaSenhaFort3@"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'MinhaSenhaFort3@' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  app:
    build:
      context: ./src
    container_name: form-app
    environment:
      DB_SERVER: "mssql"
      DB_USER: "sa"
      DB_PASSWORD: "MinhaSenhaFort3@"
      DB_NAME: "appdb"
    ports:
      - "8000:8000"
    depends_on:
      mssql:
        condition: service_healthy

volumes:
  mssql_data: