apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: form-app-db
  namespace: form-app-dev
spec:
  encryptedData:
    # Este valor deve ser gerado rodando: kubeseal < secret-db.yaml > sealed-secret.yaml
    DB_SERVER: "AgA0A...exemplo-criptografado...A="
    DB_USER: "AgA0A...exemplo-criptografado...A="
    DB_PASSWORD: "AgA0A...exemplo-criptografado...A="
    DB_NAME: "AgA0A...exemplo-criptografado...A="
  template:
    metadata:
      labels:
        app: form-app
      name: form-app-db
      namespace: form-app-dev
    type: Opaque
