apiVersion: v1
kind: Secret
metadata:
  name: form-app-db
  namespace: form-app-dev
type: Opaque
stringData:
  DB_SERVER: "100.100.100.104"
  DB_USER: "formapp_dev"
  DB_PASSWORD: "SenhaDev@123"
  DB_NAME: "appdb_dev"
