apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-app
  namespace: form-app-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: form-app
  template:
    metadata:
      labels:
        app: form-app
    spec:
      containers:
        - name: form-app
          image: fcavarzare/form-app:e0795fe2156e59d740c465728e942daea7bc1613
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: form-app-db
                  key: DB_SERVER
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: form-app-db
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: form-app-db
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: form-app-db
                  key: DB_NAME
