apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: form-app-db
  namespace: form-app-prod
spec:
  encryptedData:
    # ATENÇÃO: Você deve gerar este valor rodando o comando kubeseal no Linux
    DB_NAME: "VALOR_PARA_GERAR_NO_LINUX"
    DB_PASSWORD: "VALOR_PARA_GERAR_NO_LINUX"
    DB_SERVER: "VALOR_PARA_GERAR_NO_LINUX"
    DB_USER: "VALOR_PARA_GERAR_NO_LINUX"
  template:
    metadata:
      name: form-app-db
      namespace: form-app-prod
    type: Opaque
