apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: form-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fcavarzare/FORM-APP.git
    targetRevision: prod
    path: deploy/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: form-app-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true