apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: form-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fcavarzare/FORM-APP.git
    targetRevision: main
    path: deploy/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: form-app-dev

  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: form-app
      namespace: form-app-dev
      jsonPointers:
        - /spec/replicas

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true